version: '3.8'

services:
  gemini-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-voice-assistant
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-models/gemini-2.0-flash-exp}
      - TZ=UTC
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: gemini-voice-assistant-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_WS_URL=${REACT_APP_WS_URL:-ws://localhost:8000}
      - NODE_ENV=production
    depends_on:
      - gemini-assistant

networks:
  default:
    name: gemini-assistant-network
